---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-healthcheck
  namespace: qooqie-production
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-healthcheck
  namespace: qooqie-production
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["pods", "deployments", "jobs", "cronjobs", "statefulset", "replicasets"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-healthcheck
  namespace: qooqie-production
subjects:
- kind: ServiceAccount
  name: k8s-healthcheck
  namespace: qooqie-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-healthcheck
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-healthcheck
  namespace: qooqie-production-resources
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["pods", "deployments", "jobs", "cronjobs", "statefulset", "replicasets"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-healthcheck
  namespace: qooqie-production-resources
subjects:
- kind: ServiceAccount
  name: k8s-healthcheck
  namespace: qooqie-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-healthcheck